# Generated by Django 2.1.7 on 2019-03-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysemStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelVoltage', models.FloatField()),
                ('panelCurrent', models.FloatField()),
                ('batteryVoltage', models.FloatField()),
                ('loadVoltage', models.FloatField()),
                ('loadCurrent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempInF', models.FloatField()),
                ('collectionTime', models.DateTimeField(verbose_name='date/time collected')),
            ],
        ),
    ]
