# Generated by Django 2.1.7 on 2019-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PLCWeather', '0003_systemstats_casetemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemstats',
            name='isAverageValue',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
